[General]
network = locking_scenario
simtime-resolution = ms

num-rngs=2

# **.workDelay = 10ms
# **.requestInterval = 1s

output-vector-file = "${resultdir}/${configname}-${runnumber}.vec"
output-scalar-file = "${resultdir}/${configname}-${runnumber}.sca"

[high_contention]
description = "High Contention"
abstract = true
**.requestInterval = exponential(2ms, 0)

[low_contention]
description = "Low Contention"
abstract = true
**.requestInterval = uniform(10ms, 5s, 0)

[Optimistic]
description = "Populates network with Optimistic Nodes and Manager"
abstract = true
*.locking_type = "Optimistic" 

[optimistic_high]
extends = high_contention,Optimistic
description = "Optimistic - High Contention"

[optimistic_low]
extends = low_contention,Optimistic
description = "Optimistic - Low Contention"

[PessimisticIdeal]
**.lockDelay = 0ms
description = "Populates network with Pessimistic Nodes and Manager, no lock delay"
abstract = true
*.locking_type = "Pessimistic" 

[PessimisticReal]
extends = PessimisticIdeal
**.lockDelay = uniform(100ms, 500ms, 1) # separate RNG channel so that the high and low contention runs can be compared
abstract = true
description = "Populates network with Pessimistic Nodes and Manager, including lock delay"

[pessimistic_high]
extends = high_contention,PessimisticIdeal
description = "Pessimistic - High Contention"


[pessimistic_low]
extends = low_contention,PessimisticIdeal
description = "Pessimistic - Low Contention"


[batch_execution_test]
# note: run from the terminal ./locking-simulation -u Cmdenv -c <batch_execution_test|other config>
extends = high_contention,PessimisticIdeal
description = "Batch Pessimistic - High Contention"
sim-time-limit=100000h
repeat=5 #note: the RNGs change every repetition
**.workDelay = 0.6s
output-vector-file = "${resultdir}/${configname}/${runnumber}.vec"
output-scalar-file = "${resultdir}/${configname}/${runnumber}.sca"